# List of exchanges to activate
active_exchanges = ["alpaca"]

[exchanges.alpaca]
# CCXT-specific ID
id = "alpaca"
api_key = "PKUUVOXC7XFJCCM2DEAO3ITLVY"
secret = "3qHA2pGPUDDSeeChm91SNiEUCuGwWWGQganZvR5zzUTD"
private = ""
# Symbols you care about for this exchange
symbols = ["BTC/USD", "ETH/USD"]
